services:
  db:
    image: postgres:17
    container_name: sinluz-db
    environment:
      POSTGRES_USER: sinluz
      POSTGRES_PASSWORD: sinluz
      POSTGRES_DB: sinluz
    ports:
      - "5432:5432"
    volumes:
      - sinluz-db-data:/var/lib/postgresql/data

volumes:
  sinluz-db-data: